spring.application.name=campusequipmentloan
# Use file-based H2 so data persists
spring.datasource.url=jdbc:h2:file:C:/Users/L14Y16W28/campusequipmentloan/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.security.user.name = Admin
spring.security.user.password = qwerty123
# Let JPA auto-create tables from @Entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
